services:
#    creador.example:
#        class: CreadorBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    creator.creatorService:
        class: CreadorBundle\Service\CreatorService
        arguments: [@creator.configCreatorService]

    creator.configCreatorService:
        class: CreadorBundle\Service\ConfigCreatorService
        arguments: [@kernel]

    creator.gitLabService:
        class: CreadorBundle\Service\GitLabService
        arguments: [%gitLabToken%, %gitLabUrl%]